### ISSUE TITLE
Randomiser for Bitcrack (bitcrackrandomiser as a pool)

### ISSUE THREAD

**Issue by ilkerccom** [brichard19/BitCrack#406]
Hello, 

I have developed a solo repository using Bitcrack and VanitySearch. If you want to participate, you can join the pool with a client whose codes are 100% open. Currently Puzzle 66, 67 and 68 are supported. The one who finds the Key gets the reward.

**Client;**
https://github.com/ilkerccom/bitcrackrandomiser

**Pool website;**
https://btcpuzzle.info

**Comment by FachruRozi77** [comment]
well there is some incompatibility betwween randomizer and opencl bitcrack. i'm using AMD VGA and randomizer send error message as 
2024-08-17 09:24:55.854 +08:00 [INF] Logger created/updated
2024-08-17 09:24:55.863 +08:00 [ERR] App [bitcrack] occured unhandled exception.
System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String s)
   at BitcrackRandomiser.Helpers.Helper.SHA256Hash(String data) in C:\Users\acer\Source\Repos\ilkerccom\bitcrackrandomiser\BitcrackRandomiser\Helpers\Helper.cs:line 169
   at BitcrackRandomiser.Helpers.Flagger.Flag(Settings settings, String hex, Int32 gpuIndex, String proofKey, String gpuName) in C:\Users\acer\Source\Repos\ilkerccom\bitcrackrandomiser\BitcrackRandomiser\Helpers\Flagger.cs:line 25
   at BitcrackRandomiser.Randomiser.JobFinished(String targetAddress, String hex, Settings settings, Boolean keyFound, Int32 gpuIndex) in C:\Users\acer\Source\Repos\ilkerccom\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 272
   at BitcrackRandomiser.Randomiser.OutputReceivedHandler(Object o, DataReceivedEventArgs e, String targetAddress, List`1 proofValues, String hex, Settings settings, Process process, Int32 gpuIndex) in C:\Users\acer\Source\Repos\ilkerccom\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 301
   at BitcrackRandomiser.Randomiser.<>c__DisplayClass8_0.<Scan>b__0(Object o, DataReceivedEventArgs s) in C:\Users\acer\Source\Repos\ilkerccom\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 209
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
2024-08-17 09:54:42.468 +08:00 [INF] Logger created/updated
2024-08-17 09:54:42.479 +08:00 [ERR] App [bitcrack] exited with [-529697949] code.
2024-08-17 10:27:14.208 +08:00 [ERR] App [bitcrack] exited.
the variable "s" in "BitcrackRandomiser.Randomiser.<>c__DisplayClass8_0.<Scan>b__0(Object o, DataReceivedEventArgs s) inside "bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 209" is empty,
